default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: line-clone_development
test:
  <<: *default
  database: line-clone_test
production:
  <<: *default
  database: line-clone_production
  username: line-clone
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432
